### ISSUE TITLE
localhost port

### ISSUE THREAD

**Issue by pathmapper** [orangemug/mapbox-gl-to-blob#2]
Not sure if it depends on the OS, but on my side the project is running at 
localhost:808**0**/example/ 
instead of 
localhost:808**1**/example/ 
as indicated in the [README.md](https://github.com/orangemug/mapbox-gl-to-blob/blob/master/README.md).

**Comment by orangemug** [comment]
It turns out that the webpack-dev-server increases the port number if there is something running on that port. I've updated the README to reflect. Thanks @pathmapper
